-- Migration 049: Fix social media screenshot pipeline
--
-- Three issues caused AI-generated lifestyle images to appear on Instagram
-- instead of real NORMA app screenshots:
--
--   1. media_assets.storage_path uses root-bucket paths
--      (e.g. 'social-images/games-list.png') but upload-media-assets.ts
--      and selectScreenshotUrl() both use the norma-screenshots/ subdirectory
--      (e.g. 'social-images/norma-screenshots/games-list.png').
--
--   2. media_assets.platform_tags = ARRAY['twitter'] for every row.
--      generate-recap-content queries by platform tag, so Instagram/TikTok/
--      Facebook posts never find a matching asset → image_url = null →
--      publishInstagramStandard throws.
--
--   3. The Supabase Storage bucket social-images/norma-screenshots/ contains
--      AI-generated lifestyle images from the pre-migration-030 DALL-E era.
--      selectScreenshotUrl() returns valid URLs that resolve to those AI images.
--      Running upload-media-assets.ts (after this migration) will overwrite
--      them with real app screenshots.
--
-- This migration:
--   A. Corrects storage_path for all media_assets rows.
--   B. Expands platform_tags to include all visual platforms.
--   C. Pauses any queued social_posts whose image_url points to the
--      norma-screenshots/ bucket path (all pre-fix posts). They will be
--      regenerated by the next 06:00 UTC cron after real screenshots are
--      uploaded via upload-media-assets.ts.
--
-- AFTER RUNNING THIS MIGRATION, execute:
--   deno run --allow-env --allow-net --allow-read \
--     supabase/assets/upload-media-assets.ts
-- to upload real screenshots and overwrite the AI-generated images.
-- ---------------------------------------------------------------------------


-- ---------------------------------------------------------------------------
-- A. Fix storage_path (add norma-screenshots/ subdirectory prefix)
-- ---------------------------------------------------------------------------
UPDATE public.media_assets
   SET storage_path = replace(storage_path, 'social-images/', 'social-images/norma-screenshots/')
 WHERE storage_path NOT LIKE '%norma-screenshots%';


-- ---------------------------------------------------------------------------
-- B. Expand platform_tags to all visual platforms
-- ---------------------------------------------------------------------------
UPDATE public.media_assets
   SET platform_tags = ARRAY['twitter', 'instagram', 'tiktok', 'facebook']
 WHERE true;


-- ---------------------------------------------------------------------------
-- C. Pause queued posts with stale/AI image URLs so they are not published
--    before real screenshots are uploaded. Only affects unpublished posts.
-- ---------------------------------------------------------------------------
UPDATE public.social_posts
   SET status       = 'paused',
       error_detail = 'Paused by migration 049: image_url pointed to AI-generated content. Regenerate after running upload-media-assets.ts.'
 WHERE status IN ('generated')
   AND published_at IS NULL
   AND image_url LIKE '%norma-screenshots%';
